server:
  port: 8080

spring:
  application.name: async-task

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: task-group
    producer:
      retries: 3
      properties:
        linger.ms: 1
    workers:
      pool: 4

  datasource:
    url: jdbc:postgresql://localhost:5432/nexign_async_task
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  logging:
    level:
      root: info